config/routes.rb
WorkLogger::Application.routes.draw do
  resources :hours

  resources :schedules

  devise_for :users

  root :to => 'welcome#index'

end

app/models/hour.rb
class Hour < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :schedule_id, :hours, :notes
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :user
  has_many :hours

  # attr_accessible :title, :body
  attr_accessible :user_id # is this safe? how to do it better?
  attr_accessible :name, :hours_allotted, :notes

  def hours_left
    hours_logged = self.hours.map(&:hours).inject(0, :+)
    self.hours_allotted - hours_logged
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/hours_controller.rb
class HoursController < ApplicationController
  # GET /hours
  # GET /hours.json
  def index
    @hours = Hour.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hours }
    end
  end

  # GET /hours/1
  # GET /hours/1.json
  def show
    @hour = Hour.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hour }
    end
  end

  # GET /hours/new
  # GET /hours/new.json
  def new
    @hour = Hour.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hour }
    end
  end

  # GET /hours/1/edit
  def edit
    @hour = Hour.find(params[:id])
  end

  # POST /hours
  # POST /hours.json
  def create
    @hour = Hour.new(params[:hour])

    respond_to do |format|
      if @hour.save
        format.html { redirect_to @hour, notice: 'Hour was successfully created.' }
        format.json { render json: @hour, status: :created, location: @hour }
      else
        format.html { render action: "new" }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hours/1
  # PUT /hours/1.json
  def update
    @hour = Hour.find(params[:id])

    respond_to do |format|
      if @hour.update_attributes(params[:hour])
        format.html { redirect_to @hour, notice: 'Hour was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hours/1
  # DELETE /hours/1.json
  def destroy
    @hour = Hour.find(params[:id])
    @hour.destroy

    respond_to do |format|
      format.html { redirect_to hours_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schedules }
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/new
  # GET /schedules/new.json
  def new
    @schedule = Schedule.new

    respond_to do |format|
      format.html # new.html.erb
      format.js # new.js.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/1/edit
  def edit
    @schedule = Schedule.find(params[:id])
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(params[:schedule])

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.js   { } # good path
        format.json { render json: @schedule, status: :created, location: @schedule }
      else
        format.html { render action: "new" }
        format.js   { render action: "new" } # bad path #TODO test
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.json
  def update
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to schedules_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    before_filter :authenticate_user!

    def index
        @schedules = Schedule.find(:all, :conditions => {:user_id => current_user.id})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hours_helper.rb
module HoursHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/hours/_form.html.erb
<%= form_for(@hour) do |f| %>
  <% if @hour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hour.errors.count, "error") %> prohibited this hour from being saved:</h2>

      <ul>
      <% @hour.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hours/edit.html.erb
<h1>Editing hour</h1>

<%= render 'form' %>

<%= link_to 'Show', @hour %> |
<%= link_to 'Back', hours_path %>

app/views/hours/index.html.erb
<h1>Listing hours</h1>

<table>
  <tr>
    <th>Hours</th>
    <th>Comments</th>
  </tr>

<% @hours.each do |hour| %>
  <tr>
    <td><%= hour.hours %></td>
    <td><%= hour.notes %></td>
    <td><%= link_to 'Show', hour %></td>
    <td><%= link_to 'Edit', edit_hour_path(hour) %></td>
    <td><%= link_to 'Destroy', hour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hour', new_hour_path %>

app/views/hours/new.html.erb
<h1>New hour</h1>

<%= form_for :hour, url: hours_path do |f| %>
    <%= f.hidden_field :schedule_id, :value => params[:schedule] %>

    <p>
    <%= f.label :hours %><br>
    <%= f.text_field :hours %>
    </p>

    <p>
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
    </p>

    <p>
    <%= f.submit %>
    </p>
<% end %>

<%= link_to 'Back', hours_path %>

app/views/hours/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_hour_path(@hour) %> |
<%= link_to 'Back', hours_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkLogger</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="page">
    <header>
      <div id="login_block">
          <%= link_to "home", "/" %>
          |
          <%= link_to "logout", destroy_user_session_path, :method => :delete %>
      </div>
    </header>

    <%= yield %>
</div>

</body>
</html>

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.hidden_field :user_id, :value => current_user.id %>
    <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    </p>

    <p>
    <%= f.label :hours_alloted %><br>
    <%= f.text_field :hours_allotted %>
    </p>

    <p>
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
    </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/_front.html.erb
<div class="schedule_info">

  <%= link_to schedule.name, schedule_path(schedule), {:class => "schedule_title"} %>

  <div id=<%= "schedule_#{schedule.id}_progress_bar" %> class="progress_bar"
    total_hours="<%= schedule.hours_allotted %>" remaining_hours="<%= schedule.hours_left %>">
    <div class="hours_left_count" style="float:left">
      <%= schedule.hours_left %>
      <span class="units_label">hrs</span>
    </div>
    <div class="hours_allotted_count" style="float:right">
      <%= schedule.hours_allotted %>
    </div>
    <%= link_to '', new_hour_path(schedule: schedule.id), {id: "schedule_#{schedule.id}_progress", class: "progress_indicator"} %> 
  </div>
</div>

<div style="display:none" id="edit_schedule_div">
</div>

app/views/schedules/_new.html.erb
<%= form_for(schedule, remote: true) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
        <% @schedule.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, :value => current_user.id %>

  <%= f.text_field :name, :placeholder => 'burndown title', :id => 'new_schedule_name_field', :class => 'new_schedule_field' %>
  <%= f.text_field :hours_allotted, :placeholder => 'hours', :id => 'new_schedule_hours_field', :class => 'new_schedule_field' %>
  <%= f.text_field :notes, :placeholder => 'notes', :id => 'new_schedule_notes_field', :class => 'new_schedule_field' %>

  <%= f.submit 'ok!', :id => 'new_schedule_submit' %>
<% end %>

app/views/schedules/_progress_bar.html.erb
<div id=<%= "schedule_#{schedule.id}_progress_bar" %> class="progress_bar"
  total_hours="<%= schedule.hours_allotted %>" remaining_hours="<%= schedule.hours_left %>">
    <div class="hours_left_count" style="float:left">
      <%= schedule.hours_left %>
      <span class="units_label">hrs</span>
    </div>
    <div class="hours_allotted_count" style="float:right">
      <%= schedule.hours_allotted %>
    </div>
    <%= link_to '', new_hour_path(schedule: schedule.id), {id: "schedule_#{schedule.id}_progress", class: "progress_indicator"} %> 
</div>

app/views/schedules/create.js.erb
$('#new_schedule_div').html('');
$('#add_new').show();
var s = $('<%=j render partial: 'schedules/front', locals: { schedule: @schedule } %>');
$('#schedule_list').append(s);
$(document).trigger("new_schedule_created");

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<h1>Listing schedules</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Hours</th>
    <th>Notes</th>
  </tr>

<% @schedules.each do |schedule| %>
  <tr>
    <td><%= schedule.name %></td>
    <td><%= schedule.hours_allotted %></td>
    <td><%= schedule.notes %></td>
    <td><%= link_to 'Show', schedule %></td>
    <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
    <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render 'form' %>
<% if false %>
<%= form_for :schedule, url: schedules_path do |f| %>
    <%= f.hidden_field :user_id, current_user.id %>

    <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    </p>

    <p>
    <%= f.label :hours_alloted %><br>
    <%= f.text_field :hours_allotted %>
    </p>

    <p>
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
    </p>

    <p>
    <%= f.submit %>
    </p>
<% end %>

<% end # if false %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/new.js.erb
$('#new_schedule_div').html('<%=j render partial: 'schedules/new', locals: { schedule: @schedule } %>');
$('#add_new').hide();

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Showing schedule: <%= @schedule.name %></h1>

<table>
  <tr>
    <th>Name</th>
    <th>Remaining Hours</th>
    <th>Total Hours</th>
    <th>Notes</th>
  </tr>

  <tr>
    <td><%= @schedule.name %></td>
    <td><%= @schedule.hours_left %></td>
    <td><%= @schedule.hours_allotted %></td>
    <td><%= @schedule.notes %></td>
  </tr>
</table>

<table>
  <tr>
    <th>Hours</th>
    <th>Comments</th>
  </tr>

<% @schedule.hours.each do |hour| %>
  <tr>
    <td><%= hour.hours %></td>
    <td><%= hour.notes %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Log new hours', new_hour_path(schedule: @schedule.id) %> |
<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>

app/views/welcome/index.html.erb
<div id="title_block">
    on da Klok
</div>


<div id="schedule_list">
    <% @schedules.each do |s| %>
        <%= render :partial => 'schedules/front', :locals => {:schedule => s} %>
    <% end %>
</div>

<div id="new_schedule_div">
</div>

<div id="add_new">
    <%= link_to '+', new_schedule_path, :remote => true %>
</div>